language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "manutencao14764"
    token:
      secure: "3XeeNc6hsgsPutz4i1G4"
jdk:
  - oraclejdk8
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
