language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "manutencao14764:master"
    token:
      secure: "3XeeNc6hsgsPutz4i1G4"
jdk:
  - oraclejdk8
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
